[build]
  command = "corepack enable && pnpm install && pnpm build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_LANGUAGE = "zh-CN"
  ENABLE_EXPERIMENTAL_COREPACK = "1"
  STRIPE_CURRENCY = "usd"
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--version"
  NEXT_PUBLIC_URL = "https://yotradellc.netlify.app"
  NEXT_PUBLIC_VERCEL_URL = "https://yotradellc.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 